poky-init-build-env: Update the build env to work in all POSIX and CSH shells
The poky-init-build-env was updated to determine the shell type and work in
all POSIX and CSH shells (within reason).  Some tricky magic was involved in
determining the type of shell in use (csh or posix), and then configuring
the directories.

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>

diff --git a/scripts/poky-env-internal b/scripts/poky-env-internal
--- a/scripts/poky-env-internal
+++ b/scripts/poky-env-internal
@@ -3,6 +3,7 @@
 # Poky Build Enviroment Setup Script
 #
 # Copyright (C) 2006-2007 OpenedHand Ltd.
+# Copyright (C) 2010 Wind River Systems
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,43 +19,68 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# It is assumed OEROOT is already defined when this is called
-if [ -z "$OEROOT" ]; then
-    echo >&2 "Error: OEROOT is not defined!"
-    return
-fi
+# Identify the shell...
+expr "$version" : '.*csh.*' > /dev/null && set CSH=csh || SH=sh
 
-if [ "x$BDIR" = "x" ]; then
-    if [ "x$1" = "x" ]; then
-        BDIR="build"
-    else
-        BDIR=`readlink -f "$1"`
-    fi
-fi
-if expr "$BDIR" : '/.*' > /dev/null ; then
-    BUILDDIR="$BDIR"
-else
-    BUILDDIR="`pwd`/$BDIR"
-fi
+# If in csh, blank out all variables we might use...
+[ -n "$CSH" ] && set SH=''
+[ -n "$CSH" ] && set BASH_SOURCE=''
+
+# Setup error processing
+[ -n "$CSH" ] && set ERR=''
+
+# It is assumed OEROOT is already defined when this is called
+[ -z "$ERR" -a -n "$CSH" -a -z "$OEROOT" ] && set ERR="Error: OEROOT is not defined!"
+[ -z "$ERR" -a -n "$SH"  -a -z "$OEROOT" ] && ERR="Error: OEROOT is not defined!"
+
+# Setup BDIR
+[ -z "$ERR" -a -n "$CSH" ] && set BDIR=''
+[ -z "$ERR" -a -n "$SH"  ] && BDIR=''
+
+[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR" -a -n "$1" ] && set BDIR=`readlink -f $1`
+[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR" -a -n "$1" ] && BDIR=`readlink -f $1`
+
+[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR" ] && set BDIR="build"
+[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR" ] && BDIR="build"
+
+[ -n "$CSH" ] && set BDIR_ABS=''
+expr "$BDIR" : '/.*' > /dev/null && [ -n "$CSH" ] && set BDIR_ABS="abs"
+expr "$BDIR" : '/.*' > /dev/null && [ -n "$SH"  ] && BDIR_ABS="abs"
+
+[ -z "$ERR" -a -n "$CSH" -a -n "$BDIR_ABS" ] && setenv BUILDDIR "$BDIR"
+[ -z "$ERR" -a -n "$SH"  -a -n "$BDIR_ABS" ] && export BUILDDIR="$BDIR"
+[ -z "$ERR" -a -n "$CSH" -a -z "$BDIR_ABS" ] && setenv BUILDDIR "`pwd`/$BDIR"
+[ -z "$ERR" -a -n "$SH"  -a -z "$BDIR_ABS" ] && export BUILDDIR="`pwd`/$BDIR"
+
+unset BDIR_ABS
 unset BDIR
 
-BITBAKEDIR="$OEROOT/bitbake$BBEXTRA/"
+[ -n "$CSH" -a "$?BBEXTRA" = "0" ] && set BBEXTRA=''
+[ -z "$ERR" -a -n "$CSH" ] && set BITBAKEDIR="$OEROOT/bitbake$BBEXTRA/" 
+[ -z "$ERR" -a -n "$SH"  ] && BITBAKEDIR="$OEROOT/bitbake$BBEXTRA/"
 
-BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
-BUILDDIR=`readlink -f "$BUILDDIR"`
-
-if ! (test -d "$BITBAKEDIR"); then
-    echo >&2 "Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"
-    return
-fi
-
-PATH="${OEROOT}/scripts:$BITBAKEDIR/bin/:$PATH"
-unset BITBAKEDIR
+# Remove any symlinks from paths
+[ -z "$ERR" -a -n "$CSH" ] && set BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
+[ -z "$ERR" -a -n "$SH"  ] && BITBAKEDIR=`readlink -f "$BITBAKEDIR"`
 
 # Used by the poky-qemu script
-export BUILDDIR
-export PATH
+[ -z "$ERR" -a -n "$CSH" ] && setenv BUILDDIR `readlink -f "$BUILDDIR"`
+[ -z "$ERR" -a -n "$SH"  ] && export BUILDDIR=`readlink -f "$BUILDDIR"`
+
+[ -z "$ERR" -a -n "$CSH" -a ! -d "$BITBAKEDIR" ] && set ERR="Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"
+[ -z "$ERR" -a -n "$SH"  -a ! -d "$BITBAKEDIR" ] && ERR="Error: The bitbake directory ($BITBAKEDIR) does not exist!  Did you source the script in the poky directory?"
+
+[ -z "$ERR" -a -n "$CSH" ] && setenv PATH "${OEROOT}/scripts:$BITBAKEDIR/bin/:$PATH"
+[ -z "$ERR" -a -n "$SH"  ] && export PATH="${OEROOT}/scripts:$BITBAKEDIR/bin/:$PATH"
+
+unset BITBAKEDIR
 
 # Stop multi byte characters breaking the patcher stuff - This is for Redhat / Fedora people really
-export LANG=C
-export BB_ENV_EXTRAWHITE="MACHINE DISTRO POKYMODE POKYLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS GIT_PROXY_COMMAND PSEUDO_DISABLED"
+[ -z "$ERR" -a -n "$CSH" ] && setenv LANG C 
+[ -z "$ERR" -a -n "$SH"  ] && export LANG=C
+
+[ -z "$ERR" -a -n "$CSH" ] && setenv BB_ENV_EXTRAWHITE "MACHINE DISTRO POKYMODE POKYLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS GIT_PROXY_COMMAND PSEUDO_DISABLED"
+[ -z "$ERR" -a -n "$SH"  ] && export BB_ENV_EXTRAWHITE="MACHINE DISTRO POKYMODE POKYLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS GIT_PROXY_COMMAND PSEUDO_DISABLED"
+
+[ -n "$ERR" ] && echo "$ERR"
+unset ERR
